rm/myrm/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('rmapp.urls')),
]

rm/rmapp/urls.py
from django.conf.urls import url
from . import views


app_name = "rmapp"
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^trashview/(?P<trash_id>[0-9]+)$', views.trash_view, name='trashview'),
    url(r'^del/(?P<trash_id>[0-9]+)$', views.rm_file_by_name, name='del'),
    url(r'^trashnew$', views.trash_new, name='trashnew'),
    url(r'^trash_delete/(?P<trash_id>[0-9]+)$',views.trash_delete, name='trash_delete'),
    url(r'^task/new/$', views.task_new, name='task_new'),
    url(r'^task/$', views.task_list, name='task_list'),
    url(r'^task/(?P<pk>\d+)/$', views.task_detail, name='task_detail'),
    url(r'^task/result/(?P<pk>\d+)/$', views.task_result, name='task_result'),
]

rm/rmapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

from .task_progress import TaskProgress

POLICIES = (
    (u'time', u'time'),
    (u'full', u'full')
)

class Trash(models.Model):

    path_trash = models.CharField(max_length=300)
    discription = models.TextField(blank=True)
    capacity = models.IntegerField(blank=True, null=True)
    policy = models.CharField(max_length=20, choices=POLICIES, default=u'Full')


    def __unicode__(self):
        return self.path_trash


class Task(models.Model):

    name = models.CharField(max_length=50, default="Task")
    state = models.IntegerField(default=TaskProgress.CREATED)

    trash = models.ForeignKey(Trash)

    dry_run = models.NullBooleanField()

    regex = models.BooleanField()
    restore = models.BooleanField()

    paths = models.TextField()

    def __unicode__(self):
        return self.name

rm/rmapp/forms.py
from django import forms
from .models import Trash,Task


class TrashForm(forms.ModelForm):
    class Meta:
        model = Trash
        fields = ('path_trash', 'discription', 'capacity', 'policy')


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('name', 'trash',
                  'dry_run','restore',
                  'regex', 'paths')

rm/rmapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .models import Trash, Task
from django.shortcuts import render, redirect
from .forms import TrashForm, TaskForm
from django.shortcuts import get_object_or_404
from task_progress import TaskProgress
from merm.trash_manager import regular_remove
from merm.trash_manager import remove_list, recover_list

import shutil
import merm.trash_manager
import json
import os
import multiprocessing


# Create your views here.
class File:
    def __init__(self, id, name, path):
        self.id = id
        self.name = name
        self.path = path


def index(request):

    trashes = Trash.objects.all()

    return render(request, 'rmapp/index.html', {"trashes": trashes})


def trash_view(request, trash_id):

    trash = get_object_or_404(Trash, pk=int(trash_id))
    with open(os.path.join(trash.path_trash, "_____111_1"),"r") as file:
        data = json.load(file)

    res = []
    counter = 0

    for key in data:
        res.append(File(counter, key, data[key]))
        counter += 1

    if request.method == "POST":
        result = request.POST.getlist('file')
        for i in result:
            merm.trash_manager.recover(res[int(i)].name, force=True, path = trash.path_trash)

    return render(request, 'rmapp/trashview.html', {'res': res, 'trash': trash})


def trash_new(request):

    form = TrashForm()

    if request.method == "POST":
        form = TrashForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            path = post.path_trash

            if not os.path.exists(path):
                os.mkdir(path)

            if not os.path.exists(os.path.join(path, "_____111_1")):
                with open(os.path.join(path, "_____111_1"), "w") as file:
                    json.dump({}, file)

            post.save()

            return redirect('rmapp:index')
    else:
        form = TrashForm()
    return render(request, 'rmapp/trashnew.html', {'form': form})


def rm_file_by_name(request, trash_id):

    trash = get_object_or_404(Trash, pk=int(trash_id))

    if request.method == "POST":
        result = request.POST
        file = result["text"]
        merm.trash_manager.remove(file,force=True, path=trash.path_trash)
        return redirect('rmapp:index')

    return render(request, 'rmapp/del.html', {})


def trash_delete(request, trash_id):

    trash = get_object_or_404(Trash, pk=int(trash_id))
    shutil.rmtree(trash.path_trash)
    trash.delete()

    return redirect('rmapp:index')


def task_new(request):
    form = TaskForm()

    if request.method == 'POST':
        form = TaskForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('rmapp:task_list')

    return render(request, 'rmapp/task_new.html', {'form': form})


def task_result(request, pk):

    task = Task.objects.get(pk=pk)

    task.state = TaskProgress.WORKING
    task.save()

    context = task_run(task)

    task.state = TaskProgress.COMPLETED
    task.save()

    return render(request, 'rmapp/task_result.html', context)


def task_list(request):

    tasks = {
        'tasks': Task.objects.order_by('name'),
    }

    return render(request, 'rmapp/task_list.html', tasks)


def task_detail(request, pk):

    task = Task.objects.get(pk=int(pk))
    form = TaskForm(instance=task)

    if request.method == "POST":
        form = TaskForm(request.POST, instance=task)

        if form.is_valid:
            form.save()
            return redirect('/task/')

    return render(request, 'rmapp/task_detail.html', {'form': form})


def task_run(task):

    mgr = multiprocessing.Manager()
    result = mgr.list()
    processes = multiprocessing.cpu_count() * 2

    tasks_pathes = task.paths.split()

    if task.restore:
        status = 'Restored'
        process_path = [ [] for i in xrange(processes)]
        for i in xrange(len(tasks_pathes)):
            process_path[i % processes].append(tasks_pathes[i])

        jobs = []
        for i in xrange(processes):
            j = multiprocessing.Process(target=restore_worker,
                                        args=(result, process_path[i], task.dry_run, True, False, task.trash.path_trash))
            jobs.append(j)

        for j in jobs:
            j.start()

        for j in jobs:
            j.join()
    elif task.regex:
        status = 'Regular removed'
        regular_remove(task.paths)
    else:
        status = 'Removed'
        process_path = [[] for i in xrange(processes)]
        for i in xrange(len(tasks_pathes)):
            process_path[i % processes].append(tasks_pathes[i])

        jobs = []
        for i in xrange(processes):
            j = multiprocessing.Process(target=remove_worker,
                                        args=(result,process_path[i], task.dry_run, True, False, task.trash.path_trash, task.trash.policy, task.trash.capacity))
            jobs.append(j)

        for j in jobs:
            j.start()

        for j in jobs:
            j.join()

    context = {
        'result': result,
        'status': status,
    }

    return context


def restore_worker(result, paths, *args, **kwargs):
    result.extend(recover_list(paths, *args, **kwargs))


def remove_worker(result, paths, *args, **kwargs):
    result.extend(remove_list(paths, *args, **kwargs))

rm/rmapp/templates/rmapp/del.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
        <form method="POST" class="post-form">{% csrf_token %}
            <p><label for="id_title">Title:</label> <input type="text" name="text" required id="id_title" /></p>
            <button type="submit" class="save btn btn-default">Delete</button>
        </form>
</body>
</html>

rm/rmapp/templates/rmapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <a href= {% url 'rmapp:task_list'%}> <h1>Tasks</h1> </a> <br>
    {% for trash in trashes %}
   <a href="/trashview/{{trash.id}}">
       <img src="/static/trash.jpeg" title="{{trash.path_trash}}">
   </a>
    {% endfor%}
    <a href="/trashnew">
       <img src="/static/plus.png" width="80">
   </a>

</body>
</html>

rm/rmapp/templates/rmapp/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>New post</h1>
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Save</button>
        </form>
</body>
</html>

rm/rmapp/templates/rmapp/task_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TASK</title>
     <div class="container">
        <form method="POST">
            {% csrf_token %}

            <table class="table">{{ form.as_table }}</table>

            <button type="submit" class="btn btn-primary">
                Save
            </button>
        </form>
    </div>
</head>
<body>

</body>
</html>

rm/rmapp/templates/rmapp/task_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <a href= {% url 'rmapp:task_new'%}>Add</a>
    <a href= {% url 'rmapp:index'%}>Main page</a>

    {% if tasks %}
        <table class="table">
            <thead>
                <th>Name</th>
                <th>Trash</th>
                <th>Dry-run</th>
                <th>Restore</th>
                <th>Regex</th>
                <th>Run</th>
            </thead>

            <tbody>
                {% for task in tasks %}
                    <tr>
                        <td><a href= {% url 'rmapp:task_detail' task.pk %}>{{ task }}</a></td>
                        <td>{{ task.wastebasket }}</td>
                        <td>{{ task.dry_run }}</td>
                        <td>{{ task.restore }}</td>
                        <td>{{ task.regex }}</td>
                        <td><a href= {% url 'rmapp:task_result' task.pk %}>RUN</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div>
            No tasks found
        </div>
    {% endif %}

</body>
</html>

rm/rmapp/templates/rmapp/task_new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>New task</h1>
        <form method="POST">
            {% csrf_token %}

            <table class="table">
                {{ form.as_table }}
            </table>

            <button type="submit" class="btn btn-primary">
                Save
            </button>

        </form>
</body>
</html>

rm/rmapp/templates/rmapp/task_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for a,b in result%}
    <p>{{status}} {{a}} to {{b}}</p>
{% endfor %}
</body>
</html>

rm/rmapp/templates/rmapp/trash_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

rm/rmapp/templates/rmapp/trashnew.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>New trash</h1>
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Save</button>
        </form>
</body>
</html>

rm/rmapp/templates/rmapp/trashview.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<p>Path: {{trash.path_trash}}</p>
<p>Capacity: {{trash.capacity}}</p>
<p>Policy: {{trash.policy}}</p>
<a>
<form method="POST" class="post-form"> {% csrf_token %}
    {% for i in res %}
        <p>{{ i.id }} {{i.name}} {{ i.path }} <input type="checkbox" name="file" value={{i.id}}></p>
    {% endfor%}
    <button type="submit" class="save btn btn-default">Recover</button>
</form>
    <a href= {% url 'rmapp:del' trash.id %}> Delete file</a>
    <a href={% url 'rmapp:trash_delete' trash.id%}>Delete trash</a>
</body>
</html>